import random
###Ips generadas por la funcion GeneradowAllowedIps
allowed_ips = ["22.246.172.128", "56.215.142.8", "143.33.166.213", "253.187.42.60",
                "104.145.124.238", "29.9.32.217", "211.125.24.24", "132.117.174.56",
                "64.189.121.220", "54.230.111.154"
]
###Ips generadas por la funcion GeneradorRemoveIps
remove_ips = ["192.168.97.225", "192.168.158.170", "192.168.201.40", "192.168.58.57",
                "192.168.23.102", "192.168.200.13", "192.168.101.210",
                "192.168.175.189", "192.168.240.78", "192.168.65.150"
]

### For the variable ip_addresses we storage the file lista_ips.txt
### The 200 ips generated by the function GeneradorIps are stored in the file lista_ips.txt
### to be able to read the file when we need it
ip_addresses = "lista_ips.txt"

#We opne the file lista_ips.txt in mode read next we rename as a "file"
with open (ip_addresses, "r")as file:

#We say that the content of the file must be read 
    file = file.read()
#We use a loop for in range of the fiel 

for lista_ip in ip_addresses:

#Make a condition when in the list of ips we found one of our allowed ips
#We print the message "Allowed IP: Welcome"
    if lista_ip in allowed_ips:
        print(f"Allowed IP: Welcome")
#Close the file
        file.close()
#id the list of ips apears in the remove_ips 
#Print the menssage "Remove IP: Access Denied" and remove the ip from the list
    elif lista_ip in remove_ips:
        print(f"Remove IP: Access Denied")
        ip_addresses.remove(lista_ip)
        #Close the file
        file.close()
        

#Funtion to generate 200 ips
def     GeneradorIps():
    
    ips = []
    for i in range(200):
        ip = f"{random.randint(1, 255)}.{random.randint(1, 255)}.{random.randint(1, 255)}.{random.randint(1, 255)}"
        ips.append(ip)
    #We open the file lista_ips.txt in mode to write and name as file
    #Next we make a loop for of the previous list of ips[] and write the ips in the file
    with open("lista_ips.txt","w") as file:
        for ip in ips:
            file.write(ips + "\n")
        file.close()

#Frunction to generate 10 ips
def     GeneradorAllowedIps():
    ips=[]
    for i in range(10):
        ip = f"{random.randint(1, 255)}.{random.randint(1, 255)}.{random.randint(1, 255)}.{random.randint(1, 255)}"
        ips.append(ip)
    return ips
#Function to generate 10 ips
def     GeneradorRemoveIps():
    ips = []
    for i in range(10):
        ip = f"{random.randint(1, 255)}.{random.randint(1, 255)}.{random.randint(1, 255)}.{random.randint(1, 255)}"
        ips.append(ip)
    return ips










